seed: 7
followup_limit: 2
logic_threshold: 0.65
plausibility_threshold: 0.65
minority_prompting: true
minority_min_share: 0.15
log_path: moderation_log.jsonl
model:
  name: openai-gpt4o
  temperature: 0.7
embedding:
  provider: openai
  model: text-embedding-3-large